package workflow

import (
	"testing"
	"time"

	persistencespb "go.temporal.io/server/api/persistence/v1"
	"go.temporal.io/server/common"
	"go.temporal.io/server/service/history/tasks"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// TestBuildIDRedirectRetryBoundaryDispatches keeps the redirect boundary explicit:
// only an unpaused retry strictly after the redirect clock may keep its timer. A
// retry ready before the redirect, paused in the future, or due exactly at the
// redirect clock must retain the established immediate ActivityTask route.
func TestBuildIDRedirectRetryBoundaryDispatches(t *testing.T) {
	fixture := newFutureRetryRedirectFixture(t, 1)
	mutableState := fixture.mutableState
	now := mutableState.timeSource.Now().UTC()
	futureRetry := fixture.futureRetries[0]
	futureRetryTimer := fixture.retryTimerTasks[0]

	newRetry := func(eventID int64, activityID string, scheduledTime time.Time, paused bool) *persistencespb.ActivityInfo {
		return &persistencespb.ActivityInfo{
			Version:          1,
			ScheduledEventId: eventID,
			StartedEventId:   common.EmptyEventID,
			ActivityId:       activityID,
			TaskQueue:        "redirect-boundary-task-queue",
			ScheduledTime:    timestamppb.New(scheduledTime),
			HasRetryPolicy:   true,
			Attempt:          2,
			Paused:           paused,
			BuildIdInfo: &persistencespb.ActivityInfo_UseWorkflowBuildIdInfo_{
				UseWorkflowBuildIdInfo: &persistencespb.ActivityInfo_UseWorkflowBuildIdInfo{
					LastUsedBuildId: redirectBenchmarkInitialBuildID,
				},
			},
		}
	}
	readyRetry := newRetry(3, "ready-retry", now.Add(-time.Nanosecond), false)
	pausedRetry := newRetry(4, "paused-retry", now.Add(time.Hour), true)
	exactlyDueRetry := newRetry(5, "exactly-due-retry", now, false)
	for _, retry := range []*persistencespb.ActivityInfo{readyRetry, pausedRetry, exactlyDueRetry} {
		mutableState.addPendingActivityInfo(retry)
		if err := mutableState.taskGenerator.GenerateActivityRetryTasks(retry); err != nil {
			t.Fatalf("generate retry timer for %d: %v", retry.GetScheduledEventId(), err)
		}
	}
	// These timers already exist in the physical queue. Pop only avoids treating
	// their creation as a task generated by the redirect below.
	mutableState.PopTasks()
	mutableState.updateActivityInfos = make(map[int64]*persistencespb.ActivityInfo)

	if err := mutableState.ApplyBuildIdRedirect(
		fixture.startingTaskEventID,
		redirectBenchmarkTargetBuildID,
		1,
	); err != nil {
		t.Fatalf("apply build ID redirect: %v", err)
	}

	activityTasks := make(map[int64]*tasks.ActivityTask)
	for _, task := range mutableState.PopTasks()[tasks.CategoryTransfer] {
		if activityTask, ok := task.(*tasks.ActivityTask); ok {
			activityTasks[activityTask.ScheduledEventID] = activityTask
		}
	}

	timerStillCurrent := futureRetryTimer.EventID == futureRetry.GetScheduledEventId() &&
		futureRetryTimer.Attempt == futureRetry.GetAttempt() &&
		futureRetryTimer.Stamp == futureRetry.GetStamp()
	if timerStillCurrent {
		if _, ok := activityTasks[futureRetry.GetScheduledEventId()]; ok {
			t.Fatal("future retry generated an immediate activity task before backoff expired")
		}
	} else {
		// The baseline invalidates the timer and preserves dispatch through an
		// immediate task. Accepting that route lets this check run against both
		// revisions while the candidate branch above proves its retained-timer path.
		if task := activityTasks[futureRetry.GetScheduledEventId()]; task == nil || task.Stamp != futureRetry.GetStamp() {
			t.Fatal("future retry has neither a current timer nor a current immediate task")
		}
	}

	for _, retry := range []*persistencespb.ActivityInfo{readyRetry, pausedRetry, exactlyDueRetry} {
		activityTask := activityTasks[retry.GetScheduledEventId()]
		if activityTask == nil {
			t.Fatalf("retry %q was not rescheduled immediately", retry.GetActivityId())
		}
		if activityTask.Stamp != retry.GetStamp() {
			t.Fatalf("retry %q task stamp = %d, want %d", retry.GetActivityId(), activityTask.Stamp, retry.GetStamp())
		}
		if retry.GetStamp() != 1 {
			t.Fatalf("retry %q stamp = %d, want 1", retry.GetActivityId(), retry.GetStamp())
		}
	}
	if got := mutableState.GetAssignedBuildId(); got != redirectBenchmarkTargetBuildID {
		t.Fatalf("assigned build ID = %q, want %q", got, redirectBenchmarkTargetBuildID)
	}
}
